programa: ejemplo_1.c ejemplo_2.c ejemplo_3.c
	gcc ejemplo_1.c -o ejemplo_1.o 
	gcc ejemplo_2.c -o ejemplo_2.o
	gcc ejemplo_3.c -o  ejemplo_3.o
compilar:
	./ejemplo_1.o
	./ejemplo_2.o
	./ejemplo_3.o


